# Generated by Django 4.1.4 on 2022-12-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('tel_movil', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
